export const ADD_CART = 'ADD_CART'
export const REDUCE_CART = 'REDUCE_CART'
export const DELETE_CART = 'DELETE_CART'
export const INIT_BUYCART = 'INIT_BUYCART'
export const SET_SCROLLTOP = 'SET_SCROLLTOP'
