export default {
    "code":"0",
    "message":"成功",
    "data":{
        "content":[
            {
                "productNo":"20042134520",
                "productName":"小台农芒果 480g~520g/份",
                "specName":"480g~520g/份",
                "stock":6,
                "sellPrice":5.92,
                "costPrice":0,
                "price":5.92,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/wHriSi6DKr8RrihDQBA3ryBPnX3YAhKF.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/wHriSi6DKr8RrihDQBA3ryBPnX3YAhKF.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":1,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20042585100",
                "productName":"泰国椰青 1个装 单果约850g/个",
                "specName":"1个装",
                "stock":2,
                "sellPrice":11.88,
                "costPrice":10,
                "price":11.88,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/stHi55ixwiSXYcYywNSffH4AFe5mzAHt.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/stHi55ixwiSXYcYywNSffH4AFe5mzAHt.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":15,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20042271880",
                "productName":"菲律宾进口香蕉(大) 840g-880g/份",
                "specName":"840g-880g",
                "stock":2,
                "sellPrice":11.35,
                "costPrice":17,
                "price":11.35,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/ncfPdp5Cp3bf84PrtkQxQNmXnXZEm8hS.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/ncfPdp5Cp3bf84PrtkQxQNmXnXZEm8hS.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":11,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20047672001",
                "productName":"鲜切一级密瓜 250g-280g",
                "specName":"250g-280g",
                "stock":2,
                "sellPrice":14.08,
                "costPrice":0,
                "price":14.08,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/Sst6KxynyCXkfpRTiNtN7QXZhRsnjfyN.png",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/Sst6KxynyCXkfpRTiNtN7QXZhRsnjfyN.png"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":0,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20044688001",
                "productName":"鲜切一级菠萝蜜 250g~270g/盒",
                "specName":"250g~270g/盒",
                "stock":2,
                "sellPrice":16.28,
                "costPrice":0,
                "price":16.28,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/HPzdWTniXDHza8d5kGrZR6aGpmtjJbWe.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/HPzdWTniXDHza8d5kGrZR6aGpmtjJbWe.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":0,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20049911001",
                "productName":"优雅的甘蔗粒 250g-270g",
                "specName":"250g-270g",
                "stock":2,
                "sellPrice":6.6,
                "costPrice":0,
                "price":6.6,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/esFA4KcK4SMGXaPrcbnMMeniDfPxrAbW.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/esFA4KcK4SMGXaPrcbnMMeniDfPxrAbW.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":0,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20053116550",
                "productName":" 番石榴(白心) 500g~550g/份",
                "specName":"500g~550g/份",
                "stock":1,
                "sellPrice":5.01,
                "costPrice":0,
                "price":5.01,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/wT3bXiXPzxBGaj6ztdA3csXp8N8JP8cG.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/wT3bXiXPzxBGaj6ztdA3csXp8N8JP8cG.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":3,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20047726850",
                "productName":"国产脐橙(小) 750g-850g/份",
                "specName":"750g-850g",
                "stock":0,
                "sellPrice":12,
                "costPrice":12,
                "price":12,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/Yy7xk5pnTRjP64QYdi5FDjXjjanTWnSN.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/Yy7xk5pnTRjP64QYdi5FDjXjjanTWnSN.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":17,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20042271800",
                "productName":"菲律宾进口香蕉 约780-820g/份",
                "specName":"约780g~820g",
                "stock":0,
                "sellPrice":10.56,
                "costPrice":10.26,
                "price":10.56,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/ncfPdp5Cp3bf84PrtkQxQNmXnXZEm8hS.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/ncfPdp5Cp3bf84PrtkQxQNmXnXZEm8hS.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":14,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20047429420",
                "productName":"火龙果 380g~420g/份",
                "specName":"380g~420g",
                "stock":0,
                "sellPrice":5.14,
                "costPrice":0,
                "price":5.14,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/N783rZ5h8dc5YhDAwwr2WniHH8tnH72B.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/N783rZ5h8dc5YhDAwwr2WniHH8tnH72B.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":7,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20047528520",
                "productName":"黑提 480g-520g/份",
                "specName":"480g-520g",
                "stock":0,
                "sellPrice":24.84,
                "costPrice":13,
                "price":24.84,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/mWKbiC8dXnC3ZmNewijBGrNzGAzAmYaC.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/mWKbiC8dXnC3ZmNewijBGrNzGAzAmYaC.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":3,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20044718001",
                "productName":"鲜切进口凤梨 250g~270g/盒",
                "specName":"250g~270g/盒",
                "stock":0,
                "sellPrice":16.28,
                "costPrice":0,
                "price":16.28,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/WMTf33iYCkpHbHpGJNNxb6HDtK8NXGRY.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/WMTf33iYCkpHbHpGJNNxb6HDtK8NXGRY.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":1,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20047726115",
                "productName":"国产脐橙(大) 1050g-1150g/份",
                "specName":"1050g-1150g",
                "stock":0,
                "sellPrice":12,
                "costPrice":12,
                "price":12,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/Yy7xk5pnTRjP64QYdi5FDjXjjanTWnSN.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/Yy7xk5pnTRjP64QYdi5FDjXjjanTWnSN.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":0,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20043650120",
                "productName":"皇冠蜜梨(小) 1.1kg-1.2kg/份",
                "specName":"1100g-1200g",
                "stock":0,
                "sellPrice":24.8,
                "costPrice":24.8,
                "price":24.8,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/hxje4TAAJFEF7wZkwJhcGa2QEtJJnSAC.png",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/hxje4TAAJFEF7wZkwJhcGa2QEtJJnSAC.png"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":0,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20050016580",
                "productName":"进口红提(大) 540g-580g/份",
                "specName":"540g-580g",
                "stock":0,
                "sellPrice":30,
                "costPrice":30,
                "price":30,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/nKyX5ijiFeGKGYenjZ2Qm637XzmY7KZC.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/nKyX5ijiFeGKGYenjZ2Qm637XzmY7KZC.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":0,
                "limitCount":0,
                "effective":true
            },
            {
                "productNo":"20042288890",
                "productName":"苹果(大) 810g-890g/份",
                "specName":"810g-890g",
                "stock":0,
                "sellPrice":20,
                "costPrice":20,
                "price":20,
                "url":"http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/PCRw8ajyYWrndNwQ65tTA8TwnrwpJXHf.jpg",
                "urls":[
                    "http://qdmosshuanan01.oss-cn-shenzhen.aliyuncs.com/mallH5/PCRw8ajyYWrndNwQ65tTA8TwnrwpJXHf.jpg"
                ],
                "desc":"",
                "status":1,
                "productType":0,
                "categoryId":13,
                "sellCount":0,
                "limitCount":0,
                "effective":true
            }
        ]
    }
}